<?php

/**
 * This is the model base class for the table "banco".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Banco".
 *
 * Columns in table "banco" available as properties of the model,
 * followed by relations of table "banco" available as properties of the model.
 *
 * @property integer $idBanco
 * @property string $nombre
 * @property string $telefono
 * @property string $direccion
 * @property integer $propio
 * @property integer $localidad_idlocalidad
 *
 * @property Localidad $localidadIdlocalidad
 * @property Cheque[] $cheques
 * @property Ctabancaria[] $ctabancarias
 */
abstract class BaseBanco extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'banco';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Banco|Bancos', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('nombre', 'required'),
			array('propio, localidad_idlocalidad', 'numerical', 'integerOnly'=>true),
			array('nombre', 'length', 'max'=>100),
			array('telefono', 'length', 'max'=>20),
			array('direccion', 'length', 'max'=>45),
			array('telefono, direccion, propio, localidad_idlocalidad', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idBanco, nombre, telefono, direccion, propio, localidad_idlocalidad', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'localidadIdlocalidad' => array(self::BELONGS_TO, 'Localidad', 'localidad_idlocalidad'),
			'cheques' => array(self::HAS_MANY, 'Cheque', 'banco_idBanco'),
			'ctabancarias' => array(self::HAS_MANY, 'Ctabancaria', 'banco_idBanco'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idBanco' => Yii::t('app', 'Id Banco'),
			'nombre' => Yii::t('app', 'Nombre'),
			'telefono' => Yii::t('app', 'Telefono'),
			'direccion' => Yii::t('app', 'Direccion'),
			'propio' => Yii::t('app', 'Propio'),
			'localidad_idlocalidad' => null,
			'localidadIdlocalidad' => null,
			'cheques' => null,
			'ctabancarias' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idBanco', $this->idBanco);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('telefono', $this->telefono, true);
		$criteria->compare('direccion', $this->direccion, true);
		$criteria->compare('propio', $this->propio);
		$criteria->compare('localidad_idlocalidad', $this->localidad_idlocalidad);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}