<?php

/**
 * This is the model base class for the table "caja".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Caja".
 *
 * Columns in table "caja" available as properties of the model,
 * followed by relations of table "caja" available as properties of the model.
 *
 * @property integer $idcaja
 * @property string $nombre
 *
 * @property Movimientocaja[] $movimientocajas
 */
abstract class BaseCaja extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'caja';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Caja|Cajas', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('nombre', 'length', 'max'=>45),
			array('nombre', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idcaja, nombre', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'movimientocajas' => array(self::HAS_MANY, 'Movimientocaja', 'caja_idcaja'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idcaja' => Yii::t('app', 'Idcaja'),
			'nombre' => Yii::t('app', 'Nombre'),
			'movimientocajas' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idcaja', $this->idcaja);
		$criteria->compare('nombre', $this->nombre, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}