<?php

/**
 * This is the model base class for the table "proveedor".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Proveedor".
 *
 * Columns in table "proveedor" available as properties of the model,
 * followed by relations of table "proveedor" available as properties of the model.
 *
 * @property integer $idproveedor
 * @property string $nombre
 * @property string $cuit
 * @property string $direccion
 * @property string $telefono
 * @property string $nombrecontacto
 * @property string $email
 * @property string $web
 * @property string $created
 * @property string $modified
 * @property integer $estado
 * @property integer $localidad_idlocalidad
 * @property integer $tipodecontribuyente_idtipocontribuyente
 *
 * @property Cheque[] $cheques
 * @property Ctacteprov[] $ctacteprovs
 * @property Detalleasiento[] $detalleasientos
 * @property Ivamovimiento[] $ivamovimientos
 * @property Localidad $localidadIdlocalidad
 * @property Tipodecontribuyente $tipodecontribuyenteIdtipocontribuyente
 */
abstract class BaseProveedor extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'proveedor';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Proveedor|Proveedors', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('nombre, cuit, estado, localidad_idlocalidad, tipodecontribuyente_idtipocontribuyente', 'required'),
			array('estado, localidad_idlocalidad, tipodecontribuyente_idtipocontribuyente, ctacteprov_idctacteprov', 'numerical', 'integerOnly'=>true),
			array('nombre, direccion, telefono, nombrecontacto, email, web', 'length', 'max'=>45),
			array('cuit', 'length', 'max'=>13,'min'=>13),
			array('created, modified', 'safe'),
			array('direccion, telefono, nombrecontacto, email, web, created, modified, ctacteprov_idctacteprov', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idproveedor, nombre, cuit, direccion, telefono, nombrecontacto, email, web, created, modified, estado, localidad_idlocalidad, tipodecontribuyente_idtipocontribuyente, ctacteprov_idctacteprov', 'safe', 'on'=>'search'),
			array('modified','default',
            	'value'=>new CDbExpression('NOW()'),
                'setOnEmpty'=>false,'on'=>'update'),
            array('created,modified','default',
                'value'=>new CDbExpression('NOW()'),
                'setOnEmpty'=>false,'on'=>'insert'),
			);
	}

	public function relations() {
		return array(
			'cheques' => array(self::HAS_MANY, 'Cheque', 'proveedor_idproveedor'),
			'ctacteprovs' => array(self::HAS_MANY, 'Ctacteprov', 'proveedor_idproveedor'),
			'detalleasientos' => array(self::HAS_MANY, 'Detalleasiento', 'proveedor_idproveedor'),
			'ivamovimientos' => array(self::HAS_MANY, 'Ivamovimiento', 'proveedor_idproveedor'),
			'localidadIdlocalidad' => array(self::BELONGS_TO, 'Localidad', 'localidad_idlocalidad'),
			'tipodecontribuyenteIdtipocontribuyente' => array(self::BELONGS_TO, 'Tipodecontribuyente', 'tipodecontribuyente_idtipocontribuyente'),
			'ctacteprovIdctacteprov' => array(self::BELONGS_TO, 'Ctacteprov', 'ctacteprov_idctacteprov'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idproveedor' => Yii::t('app', 'Idproveedor'),
			'nombre' => Yii::t('app', 'Nombre'),
			'cuit' => Yii::t('app', 'Cuit'),
			'direccion' => Yii::t('app', 'Direccion'),
			'telefono' => Yii::t('app', 'Telefono'),
			'nombrecontacto' => Yii::t('app', 'Nombrecontacto'),
			'email' => Yii::t('app', 'Email'),
			'web' => Yii::t('app', 'Web'),
			'created' => Yii::t('app', 'Created'),
			'modified' => Yii::t('app', 'Modified'),
			'estado' => Yii::t('app', 'Estado'),
			'localidad_idlocalidad' => null,
			'tipodecontribuyente_idtipodecontribuyente' => Yii::t('app', 'Tipo contribuyente'),
			'cheques' => null,
			'ctacteprovs' => null,
			'detalleasientos' => null,
			'ivamovimientos' => null,
			'localidadIdlocalidad' => null,
			'tipodecontribuyenteIdtipocontribuyente' => null,
		
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idproveedor', $this->idproveedor);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('cuit', $this->cuit, true);
		$criteria->compare('direccion', $this->direccion, true);
		$criteria->compare('telefono', $this->telefono, true);
		$criteria->compare('nombrecontacto', $this->nombrecontacto, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('web', $this->web, true);
		$criteria->compare('created', $this->created, true);
		$criteria->compare('modified', $this->modified, true);
		$criteria->compare('estado', $this->estado);
		$criteria->compare('localidad_idlocalidad', $this->localidad_idlocalidad);
		$criteria->compare('tipodecontribuyente_idtipocontribuyente', $this->tipodecontribuyente_idtipocontribuyente);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}