<?php

/**
 * This is the model base class for the table "empresa".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Empresa".
 *
 * Columns in table "empresa" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $idempresa
 * @property string $razonsocial
 * @property string $nombrefantasia
 * @property string $cuit
 * @property string $direccion
 * @property string $telefono
 * @property string $telefax
 * @property string $email
 * @property string $tiposociedad
 * @property integer $localidad_idlocalidad
 * @property string $logo
 * @property string $web
 *
 */
abstract class BaseEmpresa extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'empresa';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Empresa|Empresas', $n);
	}

	public static function representingColumn() {
		return 'razonsocial';
	}

	public function rules() {
		return array(
			array('idempresa, razonsocial, localidad_idlocalidad, cuit', 'required'),
			array('idempresa, localidad_idlocalidad', 'numerical', 'integerOnly'=>true),
			array('razonsocial, nombrefantasia', 'length', 'max'=>200),
			array('cuit, direccion, telefono, telefax, email, tiposociedad, web', 'length', 'max'=>45),
			array('logo', 'length', 'max'=>255),
			array('nombrefantasia,  direccion, telefono, telefax, email, tiposociedad, logo, web', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idempresa, razonsocial, nombrefantasia, cuit, direccion, telefono, telefax, email, tiposociedad, localidad_idlocalidad, logo, web', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idempresa' => Yii::t('app', 'Idempresa'),
			'razonsocial' => Yii::t('app', 'Razon Social'),
			'nombrefantasia' => Yii::t('app', 'Nombre fantasia'),
			'cuit' => Yii::t('app', 'Cuit'),
			'direccion' => Yii::t('app', 'Dirección'),
			'telefono' => Yii::t('app', 'Teléfono'),
			'telefax' => Yii::t('app', 'Telefax'),
			'email' => Yii::t('app', 'Email'),
			'tiposociedad' => Yii::t('app', 'Tipo de Sociedad'),
			'localidad_idlocalidad' => Yii::t('app', 'Localidad'),
			'logo' => Yii::t('app', 'Logo'),
			'web' => Yii::t('app', 'Web'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idempresa', $this->idempresa);
		$criteria->compare('razonsocial', $this->razonsocial, true);
		$criteria->compare('nombrefantasia', $this->nombrefantasia, true);
		$criteria->compare('cuit', $this->cuit, true);
		$criteria->compare('direccion', $this->direccion, true);
		$criteria->compare('telefono', $this->telefono, true);
		$criteria->compare('telefax', $this->telefax, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('tiposociedad', $this->tiposociedad, true);
		$criteria->compare('localidad_idlocalidad', $this->localidad_idlocalidad);
		$criteria->compare('logo', $this->logo, true);
		$criteria->compare('web', $this->web, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}