<?php

/**
 * This is the model base class for the table "notadebitoprov".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Notadebitoprov".
 *
 * Columns in table "notadebitoprov" available as properties of the model,
 * followed by relations of table "notadebitoprov" available as properties of the model.
 *
 * @property integer $idnotadebitoprov
 * @property integer $nronotadebitoprov
 * @property string $fecha
 * @property string $descripcion
 * @property integer $proveedor_idproveedor
 * @property integer $estado
 * @property double $iva
 * @property double $percepcionIIBB
 * @property double $importebruto
 * @property double $ivatotal
 * @property double $importeneto
 * @property double $importeIIBB
 * @property integer $asiento_idasiento
 * @property integer $cuenta_idcuenta
 *
 * @property Asiento[] $asientos
 */
abstract class BaseNotadebitoprov extends GxActiveRecord {
	public $vista;
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'notadebitoprov';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Notadebitoprov|Notadebitoprovs', $n);
	}

	public static function representingColumn() {
		return 'fecha';
	}

	public function rules() {
		return array(
			array('nronotadebitoprov, fecha, proveedor_idproveedor, iva, importeneto, cuenta_idcuenta', 'required'),
			array('nronotadebitoprov, proveedor_idproveedor, estado, asiento_idasiento, cuenta_idcuenta', 'numerical', 'integerOnly'=>true),
			array('iva, percepcionIIBB, importebruto, ivatotal, importeneto, importeIIBB', 'numerical'),
			array('descripcion', 'length', 'max'=>255),
			array('descripcion, estado, percepcionIIBB, importebruto, ivatotal, importeIIBB, asiento_idasiento', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idnotadebitoprov, nronotadebitoprov, fecha, descripcion, proveedor_idproveedor, estado, iva, percepcionIIBB, importebruto, ivatotal, importeneto, importeIIBB, asiento_idasiento, cuenta_idcuenta', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'asientos' => array(self::HAS_MANY, 'Asiento', 'notadebitoprov_idnotadebitoprov'),
			'asientoIdasiento' => array(self::BELONGS_TO, 'Asiento', 'asiento_idasiento'),
			'proveedorIdproveedor' => array(self::BELONGS_TO, 'Proveedor', 'proveedor_idproveedor'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idnotadebitoprov' => Yii::t('app', 'Idnotadebitoprov'),
			'nronotadebitoprov' => Yii::t('app', 'Nro. Nota débito'),
			'fecha' => Yii::t('app', 'Fecha'),
			'descripcion' => Yii::t('app', 'Descripción'),
			'proveedor_idproveedor' => Yii::t('app', 'Proveedor'),
			'estado' => Yii::t('app', 'Estado'),
			'iva' => Yii::t('app', 'IVA'),
			'percepcionIIBB' => Yii::t('app', 'Percepcion IIBB'),
			'importebruto' => Yii::t('app', 'Importebruto'),
			'ivatotal' => Yii::t('app', 'Importe IVA'),
			'importeneto' => Yii::t('app', 'Importe Neto'),
			'importeIIBB' => Yii::t('app', 'Importe IIBB'),
			'asiento_idasiento' => Yii::t('app', 'Asiento'),
			'cuenta_idcuenta' => Yii::t('app', 'Cuenta contable relacionada'),
			'asientos' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idnotadebitoprov', $this->idnotadebitoprov);
		$criteria->compare('nronotadebitoprov', $this->nronotadebitoprov);
		$criteria->compare('fecha', $this->fecha, true);
		$criteria->compare('descripcion', $this->descripcion, true);
		$criteria->compare('proveedor_idproveedor', $this->proveedor_idproveedor);
		$criteria->compare('estado', $this->estado);
		$criteria->compare('iva', $this->iva);
		$criteria->compare('percepcionIIBB', $this->percepcionIIBB);
		$criteria->compare('importebruto', $this->importebruto);
		$criteria->compare('ivatotal', $this->ivatotal);
		$criteria->compare('importeneto', $this->importeneto);
		$criteria->compare('importeIIBB', $this->importeIIBB);
		$criteria->compare('asiento_idasiento', $this->asiento_idasiento);
		$criteria->compare('cuenta_idcuenta', $this->cuenta_idcuenta);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
			'sort' => array(
					'defaultOrder'=>'fecha ASC',
			)
		));
	}
	public function behaviors()
		{
			 return array(
		    	'datetimeI18NBehavior' => array('class' => 'ext.DateTimeI18NBehavior.DateTimeI18NBehavior'),
		    	'ERememberFiltersBehavior' => array(
	            	'class' => 'application.components.ERememberFiltersBehavior',
	               	'defaults'=>array(),           /* optional line */
	               	'defaultStickOnClear'=>false   /* optional line */
	           	),
		    
		   ); // 'ext' is in Yii 1.0.8 version. For early versions, use 'application.extensions' instead.
		}	
}