<?php

/**
 * This is the model base class for the table "ordendepago".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Ordendepago".
 *
 * Columns in table "ordendepago" available as properties of the model,
 * followed by relations of table "ordendepago" available as properties of the model.
 *
 * @property integer $idordendepago
 * @property string $fecha
 * @property string $descripcionordendepago
 * @property double $importe
 * @property integer $ctacteprov_idctacteprov
 *
 * @property Detalleordendepago[] $detalleordendepagos
 * @property Ctacteprov $ctacteprovIdctacteprov
 */
abstract class BaseOrdendepago extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'ordendepago';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Ordendepago|Ordendepagos', $n);
	}

	public static function representingColumn() {
		return 'fecha';
	}

	public function rules() {
		return array(
			array('fecha,importe, ctacteprov_idctacteprov', 'required'),
			array('ctacteprov_idctacteprov', 'numerical', 'integerOnly'=>true),
			array('importe', 'numerical'),
			array('descripcionordendepago', 'length', 'max'=>45),
			array('descripcionordendepago, importe', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idordendepago, fecha, descripcionordendepago, importe, ctacteprov_idctacteprov', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'detalleordendepagos' => array(self::HAS_MANY, 'Detalleordendepago', 'ordendepago_idordendepago'),
			'ctacteprovIdctacteprov' => array(self::BELONGS_TO, 'Ctacteprov', 'ctacteprov_idctacteprov'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idordendepago' => Yii::t('app', 'Idordendepago'),
			'fecha' => Yii::t('app', 'Fecha'),
			'descripcionordendepago' => Yii::t('app', 'Descripcionordendepago'),
			'importe' => Yii::t('app', 'Importe'),
			'ctacteprov_idctacteprov' => Yii::t('app', 'Proveedor'),
			'detalleordendepagos' => null,
			'ctacteprovIdctacteprov' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idordendepago', $this->idordendepago);
		$criteria->compare('fecha', $this->fecha, true);
		$criteria->compare('descripcionordendepago', $this->descripcionordendepago, true);
		$criteria->compare('importe', $this->importe);
		$criteria->compare('ctacteprov_idctacteprov', $this->ctacteprov_idctacteprov);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
			'sort' => array(
					'defaultOrder'=>'fecha ASC',
			)
		));
	}
	public function behaviors()
		{
			 return array(
		    	'datetimeI18NBehavior' => array('class' => 'ext.DateTimeI18NBehavior.DateTimeI18NBehavior'),
		    	'ERememberFiltersBehavior' => array(
	            	'class' => 'application.components.ERememberFiltersBehavior',
	               	'defaults'=>array(),           /* optional line */
	               	'defaultStickOnClear'=>false   /* optional line */
	           	),
		    
		   ); // 'ext' is in Yii 1.0.8 version. For early versions, use 'application.extensions' instead.
		}
}