<?php

/**
 * This is the model base class for the table "chequera".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Chequera".
 *
 * Columns in table "chequera" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $idchequera
 * @property string $nombre
 * @property string $descripcion
 * @property integer $estado
 * @property string $tipo
 * @property integer $ctabancaria_idctabancaria
 *
 */
abstract class BaseChequera extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'chequera';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Chequera|Chequeras', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('nombre, tipo, ctabancaria_idctabancaria', 'required'),
			array('estado, ctabancaria_idctabancaria', 'numerical', 'integerOnly'=>true),
			array('nombre, descripcion, tipo', 'length', 'max'=>100),
			array('descripcion, estado', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idchequera, nombre, descripcion, estado, tipo, ctabancaria_idctabancaria', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		'ctabancariaIdctabancaria' => array(self::BELONGS_TO, 'Ctabancaria', 'ctabancaria_idctabancaria'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idchequera' => Yii::t('app', 'Idchequera'),
			'nombre' => Yii::t('app', 'Nombre'),
			'descripcion' => Yii::t('app', 'Descripcion'),
			'estado' => Yii::t('app', 'Estado'),
			'tipo' => Yii::t('app', 'Tipo de cheques'),
			'ctabancaria_idctabancaria' => Yii::t('app', 'Cuenta Bancaria relacionada'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idchequera', $this->idchequera);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('descripcion', $this->descripcion, true);
		$criteria->compare('estado', $this->estado);
		$criteria->compare('tipo', $this->tipo, true);
		$criteria->compare('ctabancaria_idctabancaria', $this->ctabancaria_idctabancaria);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
	private $desactivadas;
	public function getdesactivadas(){
		$var=$this->find("estado=:estado",array(':estado'=>0));
		return $var;
	}
}