<?php

/**
 * This is the model base class for the table "ctabancaria".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Ctabancaria".
 *
 * Columns in table "ctabancaria" available as properties of the model,
 * followed by relations of table "ctabancaria" available as properties of the model.
 *
 * @property integer $idctabancaria
 * @property string $nombre
 * @property string $descripcion
 * @property integer $tipoctabancaria_idtipoctabancaria
 * @property integer $cuenta_idcuenta
 * @property integer $banco_idBanco
 * @property integer $estado
 *
 * @property Banco $bancoIdBanco
 * @property Cuenta $cuentaIdcuenta
 * @property Movimientobanco[] $movimientobancos
 */
abstract class BaseCtabancaria extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'ctabancaria';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Ctabancaria|Ctabancarias', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('nombre,  cuenta_idcuenta, banco_idBanco', 'required'),
			array('cuenta_idcuenta, banco_idBanco, estado', 'numerical', 'integerOnly'=>true),
			array('nombre', 'length', 'max'=>100),
			array('descripcion', 'safe'),
			array('descripcion, estado', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idctabancaria, nombre, descripcion, cuenta_idcuenta, banco_idBanco, estado', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'bancoIdBanco' => array(self::BELONGS_TO, 'Banco', 'banco_idBanco'),
			'cuentaIdcuenta' => array(self::BELONGS_TO, 'Cuenta', 'cuenta_idcuenta'),
			'movimientobancos' => array(self::HAS_MANY, 'Movimientobanco', 'ctabancaria_idctabancaria'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idctabancaria' => Yii::t('app', 'Idctabancaria'),
			'nombre' => Yii::t('app', 'Nombre cuenta'),
			'descripcion' => Yii::t('app', 'Descripcion'),
			'cuenta_idcuenta' => null,
			'banco_idBanco' => null,
			'estado' => Yii::t('app', 'Estado'),
			'bancoIdBanco' => null,
			'cuentaIdcuenta' => null,
			'movimientobancos' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idctabancaria', $this->idctabancaria);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('descripcion', $this->descripcion, true);
		$criteria->compare('cuenta_idcuenta', $this->cuenta_idcuenta);
		$criteria->compare('banco_idBanco', $this->banco_idBanco);
		$criteria->compare('estado', $this->estado);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
	private $desactivadas;
	public function getdesactivadas(){
		$var=$this->find("estado=:estado",array(':estado'=>0));
		return $var;
	}
	private $nombcta;
	public function getnombcta(){
		return $this->nombre." - ".$this->bancoIdBanco;
		
	}
}