<?php

/**
 * This is the model base class for the table "detalleordendepago".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Detalleordendepago".
 *
 * Columns in table "detalleordendepago" available as properties of the model,
 * followed by relations of table "detalleordendepago" available as properties of the model.
 *
 * @property integer $iddetalleordendepago
 * @property integer $tipoordendepago
 * @property double $importe
 * @property string $transferenciabanco
 * @property string $chequefechacobro
 * @property string $chequefechaemision
 * @property string $nrocheque
 * @property integer $chequebanco
 * @property integer $ordendepago_idordendepago
 *
 * @property Ordendepago $ordendepagoIdordendepago
 */
abstract class BaseDetalleordendepago extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'detalleordendepago';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Detalleordendepago|Detalleordendepagos', $n);
	}

	public static function representingColumn() {
		return 'transferenciabanco';
	}

	public function rules() {
		return array(
			array('tipoordendepago, importe', 'required'),
			array('tipoordendepago, idcheque, chequebanco, ordendepago_idordendepago, caja_idcaja, chequera', 'numerical', 'integerOnly'=>true),
			array('importe', 'numerical'),
			array('transferenciabanco,chequetitular,chequecuittitular', 'length', 'max'=>100),
			array('nrocheque', 'length', 'max'=>20),
			array('chequefechacobro, chequefechaingreso', 'safe'),
			array('tipoordendepago, importe, transferenciabanco, idcheque, chequefechacobro, chequefechaingreso, nrocheque, chequebanco, chequetitular, chequecuittitular, caja_idcaja, chequera', 'default', 'setOnEmpty' => true, 'value' => null),
			array('iddetalleordendepago, tipoordendepago, importe, idcheque, transferenciabanco, chequefechacobro, chequefechaingreso, nrocheque, chequebanco, ordendepago_idordendepago,chequetitular,chequecuittitular, caja_idcaja, chequera', 'safe', 'on'=>'search'),
			array('tipoordendepago','validarDatosCheque'),
			array('tipoordendepago','validarDatosTransfe'),
			array('idcheque','validarChequeEstado'),
			//array('idcheque','validarEstadoCheque'), esto para ver si estaba en estado de cobro el cheque pero no se va a usar
		);
	}

	public function relations() {
		return array(
			'ordendepagoIdordendepago' => array(self::BELONGS_TO, 'Ordendepago', 'ordendepago_idordendepago'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'iddetalleordendepago' => Yii::t('app', 'Iddetalleordendepago'),
			'tipoordendepago' => Yii::t('app', 'Tipoordendepago'),
			'importe' => Yii::t('app', 'Importe'),
			'transferenciabanco' => Yii::t('app', 'Cta.Bancaria'),
			'chequefechacobro' => Yii::t('app', 'Fecha cobro'),
			'chequefechaingreso' => Yii::t('app', 'Fecha Recepción'),
			'idcheque' => Yii::t('app', 'Id. Cheque'),
			'chequetitular' => Yii::t('app', 'Titular'),
			'chequecuittitular' => Yii::t('app', 'CUIT Titular'),
			'nrocheque' => Yii::t('app', 'Nro. cheque'),
			'chequebanco' => Yii::t('app', 'Banco'),
			'ordendepago_idordendepago' => null,
			'ordendepagoIdordendepago' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('iddetalleordendepago', $this->iddetalleordendepago);
		$criteria->compare('tipoordendepago', $this->tipoordendepago);
		$criteria->compare('importe', $this->importe);
		$criteria->compare('transferenciabanco', $this->transferenciabanco, true);
		$criteria->compare('idcheque', $this->idcheque, true);
		$criteria->compare('chequefechacobro', $this->chequefechacobro, true);
		$criteria->compare('chequefechaingreso', $this->chequefechaingreso, true);
		$criteria->compare('chequetitular', $this->chequetitular, true);
		$criteria->compare('chequecuittitular', $this->chequecuittitular, true);
		$criteria->compare('nrocheque', $this->nrocheque, true);
		$criteria->compare('chequebanco', $this->chequebanco);
		
		$criteria->compare('caja_idcaja', $this->caja_idcaja);
		$criteria->compare('chequera', $this->chequera);
		$criteria->compare('ordendepago_idordendepago', $this->ordendepago_idordendepago);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
	public function behaviors()
		{
			 return array(
		    	'datetimeI18NBehavior' => array('class' => 'ext.DateTimeI18NBehavior.DateTimeI18NBehavior'),
		    	'ERememberFiltersBehavior' => array(
	            	'class' => 'application.components.ERememberFiltersBehavior',
	               	'defaults'=>array(),           /* optional line */
	               	'defaultStickOnClear'=>false   /* optional line */
	           	),
		    
		   ); // 'ext' is in Yii 1.0.8 version. For early versions, use 'application.extensions' instead.
		}
	public function validarDatosCheque($attribute,$params){
      	
    	if( $this->tipoordendepago == 1){
    		
    		switch (true){
    			case ($this->chequera == null):
    				$this->addError('chequera', 'Chequera No puede ser nula');
    				break;
    			case ($this->chequefechaingreso == null):
    				$this->addError('chequefechaingreso', 'Fecha recepción No puede ser nulo');
    				break;
    			case ($this->chequetitular == null):
    				$this->addError('chequetitular', 'Titular no puede ser nulo');
    				break;
    			case ($this->chequecuittitular == null):
    				$this->addError('chequecuittitular', 'CUIT no puede ser nulo');
    				break;
    			case ($this->chequefechacobro == null):
    				$this->addError('chequefechacobro', 'Fecha Cobro No puede ser nulo');
    				break;
    			case ($this->nrocheque == null):
    				$this->addError('nrocheque', 'Nro. Cheque No puede ser nulo');
    				break;
    			
    		}
    	}
    }
	public function validarDatosTransfe($attribute,$params){
      	
    	if( $this->tipoordendepago == 2 && $this->transferenciabanco == null){
   				$this->addError('transferenciabanco', 'No puede ser nulo');
  			}
    }
	public function validarChequeEstado($attribute,$params){
      	if($this->tipoordendepago == 3){  // es un endosaje?
		$modelcheque=Cheque::model()->findByPk($this->idcheque);
      	
    	if( $modelcheque->estado != 2){
    		if($modelcheque->estado == 3){
    		$this->addError('idcheque', 'Cheque cobrado por caja.');
		}
    	if($modelcheque->estado == 4){
    		$this->addError('idcheque', 'Cheque endozado.');
		}
   	  }
	 }
	}
}