<?php

/**
 * This is the model base class for the table "producto".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Producto".
 *
 * Columns in table "producto" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $idproducto
 * @property string $nombre
 * @property string $descripcion
 * @property double $precio
 * @property integer $estado
 * @property string $unidad
 * @property double $cantidadventa
 * @property integer $cuenta_idcuenta
 *
 */
abstract class BaseProducto extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'producto';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Producto|Productos', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('nombre, estado, cuenta_idcuenta', 'required'),
			array('estado, cuenta_idcuenta', 'numerical', 'integerOnly'=>true),
			array('precio, cantidadventa', 'numerical'),
			array('nombre, descripcion, unidad', 'length', 'max'=>45),
			array('descripcion, precio, unidad, cantidadventa', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idproducto, nombre, descripcion, precio, estado, unidad, cantidadventa, cuenta_idcuenta', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idproducto' => Yii::t('app', 'Idproducto'),
			'nombre' => Yii::t('app', 'Nombre'),
			'descripcion' => Yii::t('app', 'Descripción'),
			'precio' => Yii::t('app', 'Precio'),
			'estado' => Yii::t('app', 'Estado'),
			'unidad' => Yii::t('app', 'Unidad de venta'),
			'cantidadventa' => Yii::t('app', 'Cantidad para la venta (Kg)'),
			'cuenta_idcuenta' => Yii::t('app', 'Cuenta contable relacionada al producto (venta)'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idproducto', $this->idproducto);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('descripcion', $this->descripcion, true);
		$criteria->compare('precio', $this->precio);
		$criteria->compare('estado', $this->estado);
		$criteria->compare('unidad', $this->unidad, true);
		$criteria->compare('cantidadventa', $this->cantidadventa);
		$criteria->compare('cuenta_idcuenta', $this->cuenta_idcuenta);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}