<?php

/**
 * This is the model base class for the table "pais".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Pais".
 *
 * Columns in table "pais" available as properties of the model,
 * followed by relations of table "pais" available as properties of the model.
 *
 * @property integer $idpais
 * @property string $nombre
 *
 * @property Provincia[] $provincias
 */
abstract class BasePais extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'pais';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Pais|Paises', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('nombre', 'required'),
			array('nombre', 'length', 'max'=>45),
			array('idpais, nombre', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'provincias' => array(self::HAS_MANY, 'Provincia', 'pais_idpais'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idpais' => Yii::t('app', 'Idpais'),
			'nombre' => Yii::t('app', 'Nombre'),
			'provincias' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idpais', $this->idpais);
		$criteria->compare('nombre', $this->nombre, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}