<?php

/**
 * This is the model base class for the table "movimientocaja".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Movimientocaja".
 *
 * Columns in table "movimientocaja" available as properties of the model,
 * followed by relations of table "movimientocaja" available as properties of the model.
 *
 * @property integer $idmovimientocaja
 * @property string $descripcion
 * @property string $fecha
 * @property integer $debeohaber
 * @property double $debe
 * @property double $haber
 * @property integer $id_de_trabajo
 * @property integer $caja_idcaja
 * @property integer $asiento_idasiento
 * @property integer $cuenta_idcuenta
 *
 * @property Asiento[] $asientos
 * @property Detallecobranza[] $detallecobranzas
 * @property Detallecompra[] $detallecompras
 * @property Detalleordendepago[] $detalleordendepagos
 * @property Detallepagos[] $detallepagoses
 * @property Caja $cajaIdcaja
 * @property Asiento $asientoIdasiento
 */
abstract class BaseMovimientocaja extends GxActiveRecord {
	public $importe, $vista;
	public $fechacobro;
	public $total_debe,$total_haber;
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'movimientocaja';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Movimientocaja|Movimientocajas', $n);
	}

	public static function representingColumn() {
		return 'fecha';
	}

	public function rules() {
		return array(
			array('descripcion, fecha, debeohaber, caja_idcaja, cuenta_idcuenta', 'required'),
			array('debeohaber, id_de_trabajo, caja_idcaja, asiento_idasiento, cuenta_idcuenta, idfactura , idcompra, iddetallecobranza, iddetalleordendepago', 'numerical', 'integerOnly'=>true),
			array('debe, haber', 'numerical'),
			array('descripcion', 'length', 'max'=>150),
			array('debe, haber, id_de_trabajo, asiento_idasiento,  idfactura , idcompra, iddetallecobranza, iddetalleordendepago', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idmovimientocaja, descripcion, fecha, debeohaber, debe, haber, id_de_trabajo, caja_idcaja, asiento_idasiento, cuenta_idcuenta,  idfactura , idcompra, iddetallecobranza, iddetalleordendepago', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'asientos' => array(self::HAS_MANY, 'Asiento', 'movimientocaja_idmovimientocaja'),
			'detallecobranzas' => array(self::HAS_MANY, 'Detallecobranza', 'movimientocaja_idmovimientocaja'),
			'detallecompras' => array(self::HAS_MANY, 'Detallecompra', 'movimientocaja_idmovimientocaja'),
			'detalleordendepagos' => array(self::HAS_MANY, 'Detalleordendepago', 'movimientocaja_idmovimientocaja'),
			'detallepagoses' => array(self::HAS_MANY, 'Detallepagos', 'movimientocaja_idmovimientocaja'),
			'cajaIdcaja' => array(self::BELONGS_TO, 'Caja', 'caja_idcaja'),
			'asientoIdasiento' => array(self::BELONGS_TO, 'Asiento', 'asiento_idasiento'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idmovimientocaja' => Yii::t('app', 'Idmovimientocaja'),
			'descripcion' => Yii::t('app', 'Descripcion'),
			'fecha' => Yii::t('app', 'Fecha'),
			'debeohaber' => Yii::t('app', 'Debeohaber'),
			'debe' => Yii::t('app', 'Debe'),
			'haber' => Yii::t('app', 'Haber'),
			'id_de_trabajo' => Yii::t('app', 'Id De Trabajo'),
			'caja_idcaja' => null,
			'asiento_idasiento' => null,
			'cuenta_idcuenta' => Yii::t('app', 'Cuenta Idcuenta'),
			'asientos' => null,
			'detallecobranzas' => null,
			'detallecompras' => null,
			'detalleordendepagos' => null,
			'detallepagoses' => null,
			'cajaIdcaja' => null,
			'asientoIdasiento' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idmovimientocaja', $this->idmovimientocaja);
		$criteria->compare('descripcion', $this->descripcion, true);
		$criteria->compare('fecha', $this->fecha, true);
		$criteria->compare('debeohaber', $this->debeohaber);
		$criteria->compare('debe', $this->debe);
		$criteria->compare('haber', $this->haber);
		$criteria->compare('id_de_trabajo', $this->id_de_trabajo);
		$criteria->compare('caja_idcaja', $this->caja_idcaja);
		$criteria->compare('asiento_idasiento', $this->asiento_idasiento);
		$criteria->compare('cuenta_idcuenta', $this->cuenta_idcuenta);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
//para listar los caja cargadas en solapas	
	public function listCajas(){
		$sql= "SELECT idcaja,nombre FROM  caja WHERE estado=1 LIMIT 10";
		$dbCommand = Yii::app()->db->createCommand($sql);
		$resultado = $dbCommand->queryAll();
		return $resultado;
	}
public function behaviors()
		{
			 return array(
		    	'datetimeI18NBehavior' => array('class' => 'ext.DateTimeI18NBehavior.DateTimeI18NBehavior'),
		    	'ERememberFiltersBehavior' => array(
	            	'class' => 'application.components.ERememberFiltersBehavior',
	               	'defaults'=>array(),           /* optional line */
	               	'defaultStickOnClear'=>false   /* optional line */
	           	),
		    
		   ); // 'ext' is in Yii 1.0.8 version. For early versions, use 'application.extensions' instead.
		}
public function compararFechas($attribute,$params)
	 {
	 	
	if(isset($this->fechacobro) && !empty($this->attributes['fecha'])) {
	  $valoresPrimera = explode ("/", $this->fechacobro);   
	  $valoresSegunda = explode ("/", $this->attributes['fecha']); 
	
	  $diaP = $valoresPrimera[0];  
	  $mesP = $valoresPrimera[1];  
	  $anyoP = $valoresPrimera[2]; 
	
	  $diaS = $valoresSegunda[0];  
	  $mesS = $valoresSegunda[1];  
	  $anyoS = $valoresSegunda[2];
	
	  $diasPJuliano = gregoriantojd($mesP, $diaP, $anyoP);  
	  $diasSJuliano = gregoriantojd($mesS, $diaS, $anyoS);     
	  
	  if(!checkdate($mesP, $diaP, $anyoP)){
	    // "La fecha ".$primera." no es v&aacute;lida";
	    $this->addError($attribute,'Los datos ingresados no son correctos.');
	  }elseif(!checkdate($mesS, $diaS, $anyoS)){
	    // "La fecha ".$segunda." no es v&aacute;lida";
	     $this->addError($attribute,'Los datos ingresados no son correctos.');
	  }else{
	    if(($diasPJuliano-$diasSJuliano)> 0){
	    	$this->addError($attribute,'La fecha ingresada debe ser mayor a la fecha de cobro');
	    	}
	    }
	  } 
	}
		
	public function obtenerDebeHaber($mes,$anio,$banco)
        {
                $criteria=new CDbCriteria;
                
                $criteria->select = array(
                	'SUM(debe) AS total_debe, SUM(haber) AS total_haber',
                );

                $criteria->condition = 'YEAR(fecha)='.$anio.' and MONTH(fecha)='.$mes.' and caja_idcaja='.$banco;
                $result = Movimientocaja::model()->find($criteria); 
                return new CActiveDataProvider($this, array(
                        'criteria'=>$criteria,
                ));
        }
}