<?php

/**
 * This is the model base class for the table "subcuenta".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Subcuenta".
 *
 * Columns in table "subcuenta" available as properties of the model,
 * followed by relations of table "subcuenta" available as properties of the model.
 *
 * @property integer $idsubcuenta
 * @property string $codigosubcta
 * @property string $nombre
 * @property integer $cuenta_idcuenta
 * @property integer $tipocuenta_idtipocuenta
 * @property integer $asentable
 *
 * @property Asiento[] $asientos
 * @property Factura[] $facturas
 * @property Cuenta $cuentaIdcuenta
 * @property Tipocuenta $tipocuentaIdtipocuenta
 */
abstract class BaseSubcuenta extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'subcuenta';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Subcuenta|Subcuentas', $n);
	}

	public static function representingColumn() {
		return 'codigosubcta';
	}

	public function rules() {
		return array(
			array('codigosubcta, nombre, cuenta_idcuenta, tipocuenta_idtipocuenta, asentable', 'required'),
			array('cuenta_idcuenta, tipocuenta_idtipocuenta, asentable', 'numerical', 'integerOnly'=>true),
			array('codigosubcta, nombre', 'length', 'max'=>45),
			array('idsubcuenta, codigosubcta, nombre, cuenta_idcuenta, tipocuenta_idtipocuenta, asentable', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'asientos' => array(self::HAS_MANY, 'Asiento', 'subcuenta_idsubcuenta'),
			'facturas' => array(self::HAS_MANY, 'Factura', 'subcuenta_idsubcuenta'),
			'cuentaIdcuenta' => array(self::BELONGS_TO, 'Cuenta', 'cuenta_idcuenta'),
			'tipocuentaIdtipocuenta' => array(self::BELONGS_TO, 'Tipocuenta', 'tipocuenta_idtipocuenta'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idsubcuenta' => Yii::t('app', 'Idsubcuenta'),
			'codigosubcta' => Yii::t('app', 'Codigosubcta'),
			'nombre' => Yii::t('app', 'Nombre'),
			'cuenta_idcuenta' => null,
			'tipocuenta_idtipocuenta' => null,
			'asentable' => Yii::t('app', 'Asentable'),
			'asientos' => null,
			'facturas' => null,
			'cuentaIdcuenta' => null,
			'tipocuentaIdtipocuenta' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idsubcuenta', $this->idsubcuenta);
		$criteria->compare('codigosubcta', $this->codigosubcta, true);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('cuenta_idcuenta', $this->cuenta_idcuenta);
		$criteria->compare('tipocuenta_idtipocuenta', $this->tipocuenta_idtipocuenta);
		$criteria->compare('asentable', $this->asentable);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}