<?php

/**
 * This is the model base class for the table "user".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "User".
 *
 * Columns in table "user" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $iduser
 * @property string $firstname
 * @property string $lastname
 * @property string $username
 * @property string $password
 * @property string $email
 *
 */
abstract class BaseUser extends GxActiveRecord {
	
	public $actualizaClave,$clavere,$reclave;
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'user';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'User|Users', $n);
	}

	public static function representingColumn() {
		return 'firstname';
	}

	public function rules() {
		return array(
			array('actualizaClave', 'boolean'),
			array('password, clavere, reclave', 'length', 'min'=>6, 'max'=>64, 'on'=>'create, update, updateClave'),
            array('reclave, clavere', 'required', 'on'=>'updateClave'),
            array('reclave', 'compare', 'compareAttribute'=>'clavere' , 'on'=>'updateClave'),
			array('firstname, lastname, username, password', 'required'),
			array('firstname, lastname', 'length', 'max'=>45),
			array('username', 'length', 'max'=>16),
			array('password', 'length', 'max'=>32,'min'=>6),
			array('email', 'length', 'max'=>255),
			array('email','email'),
			array('email', 'default', 'setOnEmpty' => true, 'value' => null),
			array('reclave, clavere', 'required', 'on'=>'updateClave'),
            array('reclave', 'compare', 'compareAttribute'=>'clavere' , 'on'=>'updateClave'),
			array('iduser, firstname, lastname, username, password, email', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'iduser' => Yii::t('app', 'Iduser'),
			'firstname' => Yii::t('app', 'Nombre'),
			'lastname' => Yii::t('app', 'Apellido'),
			'username' => Yii::t('app', 'Usuario'),
			'password' => Yii::t('app', 'Password'),
			'email' => Yii::t('app', 'Email'),
			'actualizaClave' => Yii::t('app','Actualizar password'),
			'reclave' => Yii::t('app', 'Confirmar password'),
			'clavere' => Yii::t('app', 'Password'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('iduser', $this->iduser);
		$criteria->compare('firstname', $this->firstname, true);
		$criteria->compare('lastname', $this->lastname, true);
		$criteria->compare('username', $this->username, true);
		$criteria->compare('password', $this->password, true);
		$criteria->compare('email', $this->email, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}