<?php

/**
 * This is the model base class for the table "provincia".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Provincia".
 *
 * Columns in table "provincia" available as properties of the model,
 * followed by relations of table "provincia" available as properties of the model.
 *
 * @property integer $idprovincia
 * @property string $nombre
 * @property integer $pais_idpais
 *
 * @property Localidad[] $localidads
 * @property Pais $paisIdpais
 */
abstract class BaseProvincia extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'provincia';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Provincia|Provincias', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('nombre, pais_idpais', 'required'),
			array('pais_idpais', 'numerical', 'integerOnly'=>true),
			array('nombre', 'length', 'max'=>45),
			array('idprovincia, nombre, pais_idpais', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'localidads' => array(self::HAS_MANY, 'Localidad', 'provincia_idprovincia'),
			'paisIdpais' => array(self::BELONGS_TO, 'Pais', 'pais_idpais'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idprovincia' => Yii::t('app', 'Idprovincia'),
			'nombre' => Yii::t('app', 'Nombre provincia'),
			'pais_idpais' => null,
			'localidads' => null,
			'paisIdpais' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idprovincia', $this->idprovincia);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('pais_idpais', $this->pais_idpais);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
			'sort' => array('defaultOrder' => array('nombre' => false)),
		));
	}
}