<?php

/**
 * This is the model base class for the table "asiento".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Asiento".
 *
 * Columns in table "asiento" available as properties of the model,
 * followed by relations of table "asiento" available as properties of the model.
 *
 * @property integer $idasiento
 * @property string $fecha
 * @property string $descripcion
 * @property double $debe
 * @property double $haber
 * @property integer $cuenta_idcuenta
 * @property integer $subcuenta_idsubcuenta
 *
 * @property Cuenta $cuentaIdcuenta
 * @property Subcuenta $subcuentaIdsubcuenta
 */
abstract class BaseAsiento extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'asiento';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Asiento|Asientos', $n);
	}

	public static function representingColumn() {
		return 'fecha';
	}

	public function rules() {
		return array(
			array('fecha, cuenta_idcuenta, subcuenta_idsubcuenta', 'required'),
			array('cuenta_idcuenta, subcuenta_idsubcuenta', 'numerical', 'integerOnly'=>true),
			array('debe, haber', 'numerical'),
			array('descripcion', 'length', 'max'=>200),
			array('descripcion, debe, haber', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idasiento, fecha, descripcion, debe, haber, cuenta_idcuenta, subcuenta_idsubcuenta', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'cuentaIdcuenta' => array(self::BELONGS_TO, 'Cuenta', 'cuenta_idcuenta'),
			'subcuentaIdsubcuenta' => array(self::BELONGS_TO, 'Subcuenta', 'subcuenta_idsubcuenta'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idasiento' => Yii::t('app', 'Idasiento'),
			'fecha' => Yii::t('app', 'Fecha'),
			'descripcion' => Yii::t('app', 'Descripcion'),
			'debe' => Yii::t('app', 'Debe'),
			'haber' => Yii::t('app', 'Haber'),
			'cuenta_idcuenta' => null,
			'subcuenta_idsubcuenta' => null,
			'cuentaIdcuenta' => null,
			'subcuentaIdsubcuenta' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idasiento', $this->idasiento);
		$criteria->compare('fecha', $this->fecha, true);
		$criteria->compare('descripcion', $this->descripcion, true);
		$criteria->compare('debe', $this->debe);
		$criteria->compare('haber', $this->haber);
		$criteria->compare('cuenta_idcuenta', $this->cuenta_idcuenta);
		$criteria->compare('subcuenta_idsubcuenta', $this->subcuenta_idsubcuenta);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}